language: node_js
node_js:
- '0.12'
env:
  global:
  - GH_REF: github.com/karthikb351/OpenCAD.git
  - secure: GwPnCcvAUL5N5v00P+W2BKCyqzg6/JHzPQbWwdAAg+F25bD9LNIcL3HjuEvDxmak6xSadSTVkPvAlyd0t/wzEW1rSJxpxnCAqz1Pq49yerc2GtkGJUWaRmKjSovzL16K0t5+kHSALWYpBLmYgBDXOBSRORTh6saJypH4n89pgAOaR1RCld6eP+oIymw8mtxOXWYcpA2qibAWCRwXB3KqlKlklppNFBlkS53OUwwbCHoem2Jh/aV4KUM98DRYKQYmdghUwNETaqRlHv5kPlgscQsU8mNAotDJuCJHnjCjpNDC3yp3xHHUaRd/oAIJJrGdrmX5QTIc92WRdVO8VYKhgRNt2nwBzBGlNPZ7QmngF4H5ovNu2BHaMvTfx866BEwOFdVxcZqGL06vpsQE6XixAR1OeXAbdQIp5nnxdLB51W1c0XrH/ym9RzI7I7FaWgLERBiqQYPSasMNP15x+qghYhhp3IhCcth+hnq5B8ReCq14dnVlPR8oQ6T8eiSm5taAOo1VhoD5KnZrJyePm+IuAnweLA3ensIXSWDWOFtJfXzFcMPpXQIaOdJcnOckZjKqC+oyXVQbxl3bvUCMo8lNvvbZ3E5qssz2EEAeLU1kS+1fwJtcVG7bRITRmjiYwRupPxOEgyH4dvMosUxL8JMZiuYspjl8clTiPn8g7byybHg=
after_success: ./deploy.sh